# ETL - Limpieza y transformaciones de los datos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Carga de datos

In [2]:
df_condiciones = pd.read_csv('datos/condiciones_climaticas.csv')
df_politicas = pd.read_csv('datos/politicas_agricolas.csv')
df_agri = pd.read_csv('datos/produccion_agricola.csv')
df_ganaderia = pd.read_csv('datos/produccion_ganadera.csv')
df_imag = pd.read_csv('datos/imagenes_metadata.csv')
df_precios = pd.read_csv('datos/precios_mercado.csv')
df_noticias = pd.read_csv('datos/noticias_agricolas.csv')
df_reportes = pd.read_csv('datos/reporte_plagas.csv')

In [3]:
df_reportes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Año                   100 non-null    int64
 1   Mes                   100 non-null    object
 2   Día                   100 non-null    int64
 3   Area_afectada         100 non-null    int64
 4   Cultivo               100 non-null    object
 5   Eficacia              100 non-null    int64
 6   Pais                  100 non-null    object
 7   Perdida_estimada      100 non-null    int64
 8   Plaga_detectada       100 non-null    object
 9   Region                100 non-null    object
 10  Severidad             100 non-null    object
 11  Tratamiento_Aplicado  100 non-null    object
dtypes: int64(5), object(7)
memory usage: 9.5+ KB

In [4]:
df_precios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fecha                864 non-null    object
 1   pais                 864 non-null    object
 2   producto             864 non-null    object
 3   precio_usd_ton       864 non-null    float64
 4   volumen_operado_ton  864 non-null    int64
 5   tendencia_30_dias    864 non-null    object
 6   mercado_principal    864 non-null    object
 7   precio_min_mes       864 non-null    float64
 8   precio_max_mes       864 non-null    float64
dtypes: float64(3), int64(1), object(5)
memory usage: 60.9+ KB

Valores nulos

In [5]:
#Valores nulos que existen
df_condiciones.isnull().sum()

anio                           0
codigo_iso                     0
dias_con_heladas               0
eventos_extremos             142
humedad_relativa_promedio      0
indice_aridez                  0
meses_estres_hidrico           0
pais                           0
precipitacion_total            0
region_nombre                  0
temperatura_maxima             0
temperatura_minima             0
temperatura_promedio           0
dtype: int64

In [6]:
df_politicas.isnull().sum()

codigo                                0
nombre_pais                           0
acuerdo_internacional_anio_firma     64
acuerdo_internacional_firmado         0
acuerdo_internacional_nombre          0
regulacion_anio_implementacion        0
regulacion_multa_hectarea           135
regulacion_porcentaje_minimo        136
regulacion_tipo                       0
regulacion_vigente                    0
subsidio_anio                         0
subsidio_beneficiarios                0
subsidio_descripcion                  0
subsidio_moneda                       0
subsidio_monto                        0
subsidio_Precio_euros                 0
subsidio_tipo                         0
dtype: int64

Limpieza de nulos

In [7]:
#Limpieza de nulos del dataframe de condiciones climáticas
df_condiciones["eventos_extremos"] = df_condiciones["eventos_extremos"].fillna("sin evento")

In [8]:
df_condiciones.isnull().sum()

anio                         0
codigo_iso                   0
dias_con_heladas             0
eventos_extremos             0
humedad_relativa_promedio    0
indice_aridez                0
meses_estres_hidrico         0
pais                         0
precipitacion_total          0
region_nombre                0
temperatura_maxima           0
temperatura_minima           0
temperatura_promedio         0
dtype: int64

In [9]:
#Limpieza de nulos del dataframe de políticas agrícolas
df_politicas['regulacion_multa_hectarea'] = df_politicas['regulacion_multa_hectarea'].fillna(0)
df_politicas['regulacion_porcentaje_minimo'] = df_politicas['regulacion_porcentaje_minimo'].fillna(0)
df_politicas['acuerdo_internacional_anio_firma'] = df_politicas['acuerdo_internacional_anio_firma'].fillna(0)

In [10]:
df_politicas.isnull().sum()

codigo                              0
nombre_pais                         0
acuerdo_internacional_anio_firma    0
acuerdo_internacional_firmado       0
acuerdo_internacional_nombre        0
regulacion_anio_implementacion      0
regulacion_multa_hectarea           0
regulacion_porcentaje_minimo        0
regulacion_tipo                     0
regulacion_vigente                  0
subsidio_anio                       0
subsidio_beneficiarios              0
subsidio_descripcion                0
subsidio_moneda                     0
subsidio_monto                      0
subsidio_Precio_euros               0
subsidio_tipo                       0
dtype: int64

Transformación de datos (fechas a datetime)

In [11]:
# Crear fecha real en plagas mapeando meses en español a números si es necesario
meses_map = {'enero':1, 'febrero':2, 'marzo':3, 'abril':4, 'mayo':5, 'junio':6, 
             'julio':7, 'agosto':8, 'septiembre':9, 'octubre':10, 'noviembre':11, 'diciembre':12}
if df_reportes['Mes'].dtype == object: # Si viene en texto
    df_reportes['Mes_Num'] = df_reportes['Mes'].str.lower().map(meses_map)
else:
    df_reportes['Mes_Num'] = df_reportes['Mes']

# Convertir a datetime
df_reportes['Fecha_Completa'] = pd.to_datetime(
    df_reportes['Año'].astype(str) + '-' + 
    df_reportes['Mes_Num'].astype(str) + '-' + 
    df_reportes['Día'].astype(str), errors='coerce'
)

In [12]:
df_reportes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Año                   100 non-null    int64
 1   Mes                   100 non-null    object
 2   Día                   100 non-null    int64
 3   Area_afectada         100 non-null    int64
 4   Cultivo               100 non-null    object
 5   Eficacia              100 non-null    int64
 6   Pais                  100 non-null    object
 7   Perdida_estimada      100 non-null    int64
 8   Plaga_detectada       100 non-null    object
 9   Region                100 non-null    object
 10  Severidad             100 non-null    object
 11  Tratamiento_Aplicado  100 non-null    object
 12  Mes_Num               100 non-null    int64
 13  Fecha_Completa        100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(6), object(7)
memory usage: 11.1+ KB

In [13]:
df_precios['fecha'] = pd.to_datetime(df_precios['fecha'])
# Creamos columnas separadas porque los modelos de Machine Learning 
# necesitan variables numéricas independientes, no una fecha completa.
df_precios['anio_precio'] = df_precios['fecha'].dt.year
df_precios['mes_precio'] = df_precios['fecha'].dt.month
df_precios['dia_precio'] = df_precios['fecha'].dt.day

In [14]:
df_precios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fecha                864 non-null    datetime64[ns]
 1   pais                 864 non-null    object
 2   producto             864 non-null    object
 3   precio_usd_ton       864 non-null    float64
 4   volumen_operado_ton  864 non-null    int64
 5   tendencia_30_dias    864 non-null    object
 6   mercado_principal    864 non-null    object
 7   precio_min_mes       864 non-null    float64
 8   precio_max_mes       864 non-null    float64
 9   anio_precio          864 non-null    int32
 10  mes_precio           864 non-null    int32
 11  dia_precio           864 non-null    int32
dtypes: datetime64[ns](1), float64(3), int32(3), int64(1), object(4)
memory usage: 71.0+ KB

In [15]:
#Pasar datos limpios a csv para usarlos
df_reportes.to_csv('datos/reportes_plagas_limpios.csv', index=False)
df_precios.to_csv('datos/precios_mercado_limpios.csv', index=False)
df_condiciones.to_csv('datos/condiciones_climaticas_limpios.csv', index=False)
df_politicas.to_csv('datos/politicas_agricolas_limpios.csv', index=False)

Anomalias en datos

In [16]:
# Transformación temporal
df_imag['fecha'] = pd.to_datetime(df_imag['fecha'])
if df_noticias['Mes'].dtype == object: # Si viene en texto
    df_noticias['Mes_Num'] = df_noticias['Mes'].str.lower().map(meses_map)
else:
    df_noticias['Mes_Num'] = df_noticias['Mes']

# Convertir a datetime
df_noticias['Fecha_Completa'] = pd.to_datetime(
    df_noticias['Año'].astype(str) + '-' + 
    df_noticias['Mes_Num'].astype(str) + '-' + 
    df_noticias['Día'].astype(str), errors='coerce'
)

In [17]:
df_imag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   imagen_id               250 non-null    object
 1   pais                    250 non-null    object
 2   region                  250 non-null    object
 3   fecha                   250 non-null    datetime64[ns]
 4   indice_ndvi_promedio    250 non-null    float64
 5   indice_ndvi_min         250 non-null    float64
 6   indice_ndvi_max         250 non-null    float64
 7   indice_evi              250 non-null    float64
 8   uso_suelo_predominante  250 non-null    object
 9   humedad_suelo_estimada  250 non-null    float64
 10  cobertura_nubes         250 non-null    float64
 11  resolucion_metros       250 non-null    int64
 12  satelite                250 non-null    object
 13  bandas_disponibles      250 non-null    object
 14  calidad_imagen          250 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(7)
memory usage: 29.4+ KB

In [18]:
df_noticias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_noticia        60 non-null     object
 1   Alemania          60 non-null     int64
 2   Argentina         60 non-null     int64
 3   Australia         60 non-null     int64
 4   Brasil            60 non-null     int64
 5   Canadá            60 non-null     int64
 6   España            60 non-null     int64
 7   Estados Unidos    60 non-null     int64
 8   India             60 non-null     int64
 9   Italia            60 non-null     int64
 10  Francia           60 non-null     int64
 11  Kenia             60 non-null     int64
 12  México            60 non-null     int64
 13  Nueva Zelanda     60 non-null     int64
 14  Rusia             60 non-null     int64
 15  China             60 non-null     int64
 16  categoria         60 non-null     object
 17  contenido         60 non-null     object
 18  Año               60 non-null     int64
 19  Mes               60 non-null     object
 20  Día               60 non-null     int64
 21  fuente            60 non-null     object
 22  impacto_cultivos  60 non-null     object
 23  severidad         60 non-null     object
 24  titular           60 non-null     object
 25  Mes_Num           60 non-null     int64
 26  Fecha_Completa    60 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(18), object(8)
memory usage: 12.8+ KB

In [19]:
df_imag.describe()

,fecha,indice_ndvi_promedio,indice_ndvi_min,indice_ndvi_max,indice_evi,humedad_suelo_estimada,cobertura_nubes,resolucion_metros
count,250,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,2026-10-27 09:01:26.400000,0.654212,0.474492,0.754120,0.786896,0.581028,0.149096,26.580000
min,2020-01-15 00:00:00,0.301000,0.208000,0.336000,0.368000,0.203000,0.001000,10.000000
25%,2023-06-15 00:00:00,0.532250,0.379250,0.612000,0.638250,0.448500,0.078750,15.000000
50%,2026-11-01 00:00:00,0.661000,0.486000,0.767500,0.799000,0.614000,0.148000,20.000000
75%,2030-03-10 00:00:00,0.792750,0.566500,0.917500,0.942750,0.725750,0.219750,30.000000
max,2033-07-20 00:00:00,0.949000,0.785000,1.171000,1.167000,0.898000,0.299000,60.000000
std,NaN,0.165820,0.132640,0.198798,0.206962,0.184385,0.084890,17.562385

In [20]:
#Transfromación de valores de nvdi correctos
df_imag['indice_ndvi_max'] = df_imag['indice_ndvi_max'].clip(lower=-1.0, upper=1.0)

In [21]:
df_imag.describe()

,fecha,indice_ndvi_promedio,indice_ndvi_min,indice_ndvi_max,indice_evi,humedad_suelo_estimada,cobertura_nubes,resolucion_metros
count,250,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,2026-10-27 09:01:26.400000,0.654212,0.474492,0.748936,0.786896,0.581028,0.149096,26.580000
min,2020-01-15 00:00:00,0.301000,0.208000,0.336000,0.368000,0.203000,0.001000,10.000000
25%,2023-06-15 00:00:00,0.532250,0.379250,0.612000,0.638250,0.448500,0.078750,15.000000
50%,2026-11-01 00:00:00,0.661000,0.486000,0.767500,0.799000,0.614000,0.148000,20.000000
75%,2030-03-10 00:00:00,0.792750,0.566500,0.917500,0.942750,0.725750,0.219750,30.000000
max,2033-07-20 00:00:00,0.949000,0.785000,1.000000,1.167000,0.898000,0.299000,60.000000
std,NaN,0.165820,0.132640,0.190894,0.206962,0.184385,0.084890,17.562385

In [22]:
df_imag.to_csv('datos/imagenes_metadata_limpias.csv', index=False)
df_noticias.to_csv('datos/noticias_agricolas_limpias.csv', index=False)